export const AppErrorCode = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  AUTH_CHANNEL_NOT_ALLOWED: 'AUTH_CHANNEL_NOT_ALLOWED',
  AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',
  AUTH_CONFIRMATION_EXPIRED: 'AUTH_CONFIRMATION_EXPIRED',
  AUTH_CONFIRMATION_REJECTED: 'AUTH_CONFIRMATION_REJECTED',
  UPBIT_AUTH_FAILED: 'UPBIT_AUTH_FAILED',
  UPBIT_RATE_LIMIT: 'UPBIT_RATE_LIMIT',
  UPBIT_ORDER_FAILED: 'UPBIT_ORDER_FAILED',
  GEMINI_UNAVAILABLE: 'GEMINI_UNAVAILABLE',
  GEMINI_QUOTA: 'GEMINI_QUOTA',
  CIRCUIT_OPEN_UPBIT: 'CIRCUIT_OPEN_UPBIT',
  CIRCUIT_OPEN_GEMINI: 'CIRCUIT_OPEN_GEMINI',
  CIRCUIT_OPEN_NETWORK: 'CIRCUIT_OPEN_NETWORK',
  CONFIG_MISSING: 'CONFIG_MISSING',
  INTERNAL: 'INTERNAL',
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];
